#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
    path: /
    controller: App\Controller\HomeController::index

app_patient:
    path: /patient
    controller: App\Controller\PatientController::index
    
app_patient:
    path: /patient/add
    controller: App\Controller\PatientController::add

app_patient:
    path: /patient/view
    controller: App\Controller\PatientController::view